import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiC,
  SiCplusplus,
  SiMysql,
  SiGnubash,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiDjango,
  SiGraphql,
  SiTailwindcss,
  SiPostgresql,
  SiApachespark,
  SiApacheairflow,
  SiDbt,
  SiDocker,
  SiLinux,
  SiGit,
  SiPostman,
  SiAnthropic,
  SiGooglegemini,
  SiFigma,
  SiSupabase,
} from "react-icons/si";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, FaPlay } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  azure: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  typescript: SiTypescript,
  python: SiPython,
  c: SiC,
  cpp: SiCplusplus,
  sql: SiMysql,
  bash: SiGnubash,
  react: SiReact,
  nextjs: SiNextdotjs,
  nodejs: SiNodedotjs,
  django: SiDjango,
  graphql: SiGraphql,
  tailwindcss: SiTailwindcss,
  postgresql: SiPostgresql,
  apacheSpark: SiApachespark,
  apacheAirflow: SiApacheairflow,
  dbt: SiDbt,
  docker: SiDocker,
  linux: SiLinux,
  git: SiGit,
  postman: SiPostman,
  playwright: FaPlay,
  anthropic: SiAnthropic,
  google: SiGooglegemini,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
